### ISSUE TITLE
Infrequent nil pointer dereferences

### ISSUE THREAD

**Issue by egibs** [chainguard-dev/bincapz#434]
Seen in the bincapz Cloud Run jobs:
```
"panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x482f5a]

goroutine 6724 [running]:
sync.(*Map).loadReadOnly(...)
	sync/map.go:114
sync.(*Map).Range(0xc0000f2400?, 0x1ed?)
	sync/map.go:478 +0x1a
github.com/chainguard-dev/bincapz/pkg/action.errIfHitOrMiss(0x0, {0x86c3de, 0x7}, {0xc0008796c0, 0xc1}, 0x0, 0x0)
	github.com/chainguard-dev/bincapz/pkg/action/scan.go:131 +0xaf
github.com/chainguard-dev/bincapz/pkg/action.recursiveScan.func1({0xc0008796c0, 0xc1})
	github.com/chainguard-dev/bincapz/pkg/action/scan.go:231 +0x2e8
github.com/chainguard-dev/bincapz/pkg/action.recursiveScan.func3()
	github.com/chainguard-dev/bincapz/pkg/action/scan.go:279 +0x70
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x50
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x96"
```

**Comment by egibs** [comment]
Failing here: https://github.com/chainguard-dev/bincapz/blob/f17fe94027e90b895dcc9c5c5b20dbd9a6a07638/pkg/action/scan.go#L131-L139
