### ISSUE TITLE
action.errIfHitOrMiss: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tstromberg** [chainguard-dev/bincapz#458]
Found while testing against the .jar file within https://bazaar.abuse.ch/sample/909a19d0de5476e249c133f73c4afa288982d05dcf4ca597fa8357d93f435c47/

```
time=2024-09-15T21:08:02.374-04:00 level=ERROR source=/Users/t/src/bincapz/pkg/action/scan.go:233 msg="unable to process ../malware/Downloads/909a19d0de5476e249c133f73c4afa288982d05dcf4ca597fa8357d93f435c47.jar: extract to temp: failed to extract ../malware/Downloads/909a19d0de5476e249c133f73c4afa288982d05dcf4ca597fa8357d93f435c47.jar: failed to open zip file ../malware/Downloads/909a19d0de5476e249c133f73c4afa288982d05dcf4ca597fa8357d93f435c47.jar: zip: not a valid zip file"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104a70eec]

goroutine 99 [running]:
sync.(*Map).loadReadOnly(...)
        /Users/t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-arm64/src/sync/map.go:114
sync.(*Map).Range(0x1400081e000?, 0x177?)
        /Users/t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-arm64/src/sync/map.go:478 +0x1c
github.com/chainguard-dev/bincapz/pkg/action.errIfHitOrMiss(0x0, {0x104e35e3c, 0x7}, {0x14000478000, 0x59}, 0x0, 0x0)
        /Users/t/src/bincapz/pkg/action/scan.go:131 +0x74
github.com/chainguard-dev/bincapz/pkg/action.recursiveScan.func1({0x14000478000, 0x59})
        /Users/t/src/bincapz/pkg/action/scan.go:237 +0x1f8
github.com/chainguard-dev/bincapz/pkg/action.recursiveScan.func3()
        /Users/t/src/bincapz/pkg/action/scan.go:288 +0x78
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/t/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x54
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        /Users/t/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x98
exit status 2
```

**Comment by egibs** [comment]
I ran into this a while back and thought I fixed it in https://github.com/chainguard-dev/bincapz/pull/435. I'll take a closer look.
